### ISSUE TITLE
Configuration Setting and Getting

### ISSUE THREAD

**Issue by vlucas** [vlucas/bulletphp#1]
Bullet needs a way to manage configuration beyond the provided way with Pimple. Some pseudocode: 

```
$app->config('some.nested.key', 'default_value_if_not_set');
```

This would make retrieving config settings easy and provide the ability to set a default value in the case the specified config key was not set.

**Comment by tablecell** [comment]
App.php
```
    public function config($name,$value){
          $fields = explode('.',$name);
      
        if('template' == $fields[0]){
        $this['template'] = array_merge($this['template'],[$fields[1] =>$value]);
            View\Template::config($this['template']);
        }
      ...  other case 
    }
```
use in some route 
```
$app->path('/member/', function($request) use($app,$spot) {

$app->config('templdate.auto_layout','user');
````
when router starts with '/member' use another layout 
 \app\templates\layout\user.html.php

**Comment by netom** [comment]
I think PHP eventually solved the original issue with the new array behaviour, and the null coalesce operator (??) (https://wiki.php.net/rfc/isset_ternary).

This code works in PHP 7.0:

`$a = null;
$a['this']['is']['a']['nested']['key'] = 'value';`

And a config value can be read just like this:

`$value = $a['does']['this']['even']['set'] ?? 'nope.';`

And of course such configuration can just be injected into $app the Pimple way.

I'm closing this issue, thanks everybody for the thoughts on the topic.
