### ISSUE TITLE
#enhancement -- server sent events 

### ISSUE THREAD

**Issue by sam2332** [vlucas/bulletphp#30]
I would love to see a new route type for server sent events filtering

material:
http://www.w3.org/TR/eventsource/
http://www.html5rocks.com/en/tutorials/eventsource/basics/ <<-- best one it shows server specs!

https://github.com/Yaffle/EventSource/blob/master/php/events.php <-- example server code

**Comment by netom** [comment]
The event source response class could be constructed and behave somewhat similarly to the chunked response implemented at https://github.com/netom/bullet-chunks, i.e. a generator function can be passed to it that would `yield $aMessage` every once in a while.

**Comment by netom** [comment]
Done in Done in 23d45d5
