### ISSUE TITLE
Raw Request Not Always Available

### ISSUE THREAD

**Issue by jcbwlkr** [vlucas/bulletphp#46]
Depending on how your app is ran, the raw body of a request might not be available inside your routes. The problem is that `\Bullet\App` instantiates a new `\Bullet\Request` which consumes the contents of `php://input` which, as is mentioned in the comments, can only be read once.

Here's the setup. Given that I have this app:

``` php
<?php

require __DIR__ . "/vendor/autoload.php";

$app = new \Bullet\App();

$app->path("/test", function($request) use($app) {
    $app->put(function($request) use($app) {
        return "You sent me: " . $request->raw();
    });
});

echo $app->run(new \Bullet\Request());
```

And my client code looks like this:

``` php
<?php

$ch = curl_init("http://127.0.0.1/test");

$body = json_encode(array("foo" => "bar"));

curl_setopt($ch, CURLOPT_POSTFIELDS,    $body);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");

curl_exec($ch);

print PHP_EOL;
```

I should get the following output

```
You sent me: {"foo":"bar"}
```

But instead I get

```
You sent me: 
```

Digging in to the issue it seems that the problem is that when I call `$app->path` to define my route, the app internally calls `$this->request()->isHHVM()` which defines a new `\Bullet\Request`. That instance of request consumes `php://input` so the instance I define in `echo $app->run(new \Bullet\Request());` doesn't see the raw request.

If I instantiate a `\Bullet\Request` before I define my app then it gets the raw body. Or if I change the last line of my server code to `echo $app->run($app->request());` I can use the instance that has the raw body.

Honestly, I'm not sure how to test this. Is it possible to inject up in to `php://input` or mock it somehow?

**Comment by netom** [comment]
This issue no longer seems to present, closing it.
