### ISSUE TITLE
Add headers before response content is set

### ISSUE THREAD

**Issue by seblucas** [vlucas/bulletphp#50]
Hi again,

I'm adding paging to my Rest API based on bullet and I'd like to add some headers (X-Total-Count and Link).

Judging by the first lines of function header in response.php adding headers is impossible if the response has no content. Is there a reason why ?

~~For now I'm storing the content of my two headers in my $app ($app["X-Total-Count"] and $app["Link"]) and I add the headers in my response handler. It does not feel right even if it works without too much work.~~ See below

Do you see a better solution ?

Thanks in advance.

**Comment by netom** [comment]
Solved, see AppTest::testSupportCustomHeaders(). Commit b4b1dd7 make Response::content() fluent, and makes it easy to build and return a response in a single expression.
