### ISSUE TITLE
'Method 'Bullet\App::share' not found'

### ISSUE THREAD

**Issue by TheNemus** [vlucas/bulletphp#72]
Apache gives me this while trying to do some DI:

$app = new Bullet\App();
$app['config'] = $app->share(function() {

```
return array(
    "database" => array(
        "username" => "root",
        "pwd" => "",
        "host" => "localhost"
    )
);
```

});

**Comment by twocore** [comment]
Since Bullet uses Pimple as DI container, you can use the following format:

``` php
$app['config'] = function() {
    return [
        // ... your configuration
    ]
};
```

The `[ ... ]` is the short syntax for `array()` in PHP >= 5.4!

You can find more infos about pimple by reading the documentation: https://github.com/silexphp/Pimple/blob/master/README.rst

**Comment by sbditto85** [comment]
The share function comes from Pimple 1.x but bullet now seems to use Pimple 3.x which defaults the the behavior of calling share. So you don't need it anymore.
