### ISSUE TITLE
composer failing to install

### ISSUE THREAD

**Issue by sam2332** [vlucas/bulletphp#81]
composer is returning the following error while installing from your README.md

```
 php composer.phar install

Loading composer repositories with package information

Updating dependencies (including require-dev)

Your requirements could not be resolved to an installable set of packages.

Problem 1
    - The requested package vlucas/bulletphp ~1.7 is satisfiable by vlucas/bulletphp[v1.7-BETA, v1.7-RC1] but these conflict with your requirements or minimum-stability.
```

**Comment by sam2332** [comment]
If i wasnt drunk i would have noticed it asking me about what version i wanted, i installed the 1.7-rc and i think its going to work fine.

**Comment by netom** [comment]
Haha ok :)

Anyway, I was going to make RC1 final if nothing breaks in production on my side and no one brings up any deadly issue.

Thank you for considering Bullet.

Cheers,

Tamas
