### ISSUE TITLE
may reversal args that $app->response($1,$2)

### ISSUE THREAD

**Issue by KatsuoAshimine** [vlucas/bulletphp#82]
may revers args.

$app->response("Hello Error!",500);
-------------------------------------------

correct )protected function responseFactory**($content=null, $statusCode=null)**

mast repair)
    public function response()
    {
        //setter
        if(func_num_args()>=2){
            //2 args setter
            **list($statusCode,$content) = func_get_args();//corrent version
            list($content,$statusCode) = func_get_args();// after version**

**Comment by netom** [comment]
The App::response() function works like this in the v2 branch, this going to go live in version 2.0.
